CREATE TABLE USERS (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username VARCHAR(20),
	password VARCHAR(255),
);

CREATE TABLE POOL (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER REFERENCES USERS
	question VARCHAR(255),
);

CREATE TABLE ANSWERS (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	text VARCHAR(255),
	pool_id INTEGER REFERENCES POOL,
);

CREATE TABLE CHOICE (
	pool_id INTEGER REFERENCES POOL,
	user_id INTEGER REFERENCES USERS,
	answer_id INTEGER REFERENCES ANSWERS,
	PRIMARY KEY (pool_id, user_id),
);


